### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by swafel** [ItsMichaelWest/itsmichaelwest.github.io#1]
iOS web app doesn't continue working when you move into new page

**Comment by ItsMichaelWest** [comment]
Closing as non-issue.

**Comment by ItsMichaelWest** [comment]
Closed as already fixed—iOS web clip functionality was removed in a recent commit. If you still have the web clip on the home screen it may continue to open the site in the "app" mode. This can be solved by removing the clip from the home screen and re-adding it.
